/* Our C code looks like this:
F90callC1.C 
Copyright 1998 Lahey Computer Systems, Inc. */                      // 30
                                                                       // 31
#include <stdio.h>                                                     // 32
#include <stdlib.h>                                                    // 33
                                                                       // 34
#define common(name) lc_##name                                         // 35
/* prepending lc_ matches name generated by LF90 */                    // 36
                                                                       // 37
extern struct {                                                          // 38                                                                     
  float total_c;                                                         // 40
  int   total_f;                                                         // 41
} common(MYCOMMON);                                                    // 42
                                                                       // 43
                                                                       // 44
int GenTable(int *start, int *end) {                                    // 45
char endstring[10];                                                    // 47
int f;                                                                 // 48
float c;                                                               // 49
FILE *output;                                                          // 50
int lines_in_table, lines_left;                                        // 51
                                                                       // 52
/* Fortran leaves us on the line just printed, so we need to output */ // 53
/* an extra newline before we do any I/O */                            // 54
    printf("\n");                                                      // 55
                                                                       // 56
    printf("IN C\n");                                                  // 57
    printf("%s%s", "Where should the table end (Enter an ", 
           "integer less than 30) ? ");                                // 58
    gets(endstring);                                                   // 59
    *end=atoi(endstring);                                              // 60
    output=fopen("F90callC.out","w");                                  // 61
    printf("Placing Fahrenheit to Centigrade table in F90CALLC.OUT\n");// 62
    lines_left = lines_in_table = *end - *start + 1;                   // 63
    for (f=*start; lines_left > 0; f++, lines_left--)                  // 64
        {                                                              // 65
        c=5./9.*(f-32);                                                // 66
        common(MYCOMMON).total_c+=c;                                   // 67
        common(MYCOMMON).total_f+=f;                                   // 68
        fprintf(output,"%d F = %f C\n",f,c);                           // 69
        }                                                              // 70
    fclose(output);                                                    // 71
    printf("Table generated\n");                                       // 72
                                                                       // 73
/* After the last thing output from C, it is easiest to stay on the */ // 74
/* same line so the next thing output from Fortran can use standard */ // 75
/* carriage control */                                                 // 76
    printf("LEAVING C"); /* note the lack of a \n */                   // 77
                                                                       // 78
/* We flush stdout to make sure all output is out of the buffers */    // 79
/* and displayed on the screen.  If we don't do this, Fortran may */   // 80
/* end up displaying its output before C */                            // 81
    fflush(stdout);                                                    // 82
                                                                       // 83
    return(lines_in_table);                                            // 84
}        
